# Generated by Django 4.2.3 on 2023-09-09 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeruser',
            name='premium',
        ),
        migrations.RemoveField(
            model_name='registeruser',
            name='spam',
        ),
    ]
