# Generated by Django 4.2.3 on 2023-09-08 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_registeruser_premium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='spamlist',
            name='spammed_user',
        ),
        migrations.RemoveField(
            model_name='spamlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='whoviewedlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='whoviewedlist',
            name='viewed_user',
        ),
        migrations.DeleteModel(
            name='BlockedList',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='SpamList',
        ),
        migrations.DeleteModel(
            name='WhoViewedList',
        ),
    ]
